In [4]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['figure.figsize'] = (10,6)

# "TD : `sklearn` & sélection de modèles"

Romain Tavenard - (Creative Commons CC BY-NC-SA)[http://creativecommons.org/licenses/by/4.0/]

Dans cette séance, nous nous focaliserons sur la sélection de modèle pour la
classification supervisée avec `sklearn`.

# Préparation des données

Nous allons travailler, pour ce TD, sur un jeu de données ultra classique en
_machine learning_ : le jeu de données "Iris". Ce jeu de données est intégré
dans `sklearn` pour être utilisé facilement.

1. Chargez ce jeu de données à l'aide de la fonction [`load_iris`](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html) du module
`sklearn.datasets`. Faites en sorte de stocker les prédicteurs dans une matrice
`X` et les classes à prédire dans un vecteur `y`. Quelles sont les dimensions
de `X` ?

In [10]:
iris = load_iris()
X = iris.data
y = iris.target

2. Découpez ce jeu de données en un jeu d'apprentissage et un jeu de test de
mêmes tailles et faites en sorte que chacune de vos variables soient
centrées-réduites.

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_tr = scaler.transform(X_train)
X_test_tr = scaler.transform(X_test)

# Le modèle `SVC` (_Support Vector Classifier_)

3. Apprenez un modèle SVM linéaire (classe [`SVC`](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) dans `sklearn`) pour votre
problème.

4. Évaluez ses performances sur votre jeu de test à l'aide de la fonction
[`accuracy_score`](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html) du module `sklearn.metrics`.

5. Faites de même avec un modèle SVM à noyau gaussien. Faites varier la valeur
de l'hyperparamètre lié à ce noyau et observez l'évolution du taux de bonnes
classifications.

# Validation croisée

Il existe dans `sklearn` de nombreux itérateurs permettant de faire de la
validation croisée, qui sont listés sur
[cette page](http://scikit-learn.org/stable/modules/classes.html#splitter-classes).

6. Définissez un objet `cv` de la classe `KFold`. Exécutez le code suivant :

In [13]:
from sklearn.model_selection import KFold
cv = KFold(n_splits=10, shuffle=True)
for train, valid in cv.split(X_train, y_train):
    print(train, valid, end='\n==\n')

[ 0  1  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 40 43 44 45 46 47 48 49 50 52 53 54
 55 56 57 58 59 60 61 62 63 64 65 67 68 69 70 71 72 73 74] [ 2  4 19 39 41 42 51 66]
==
[ 0  1  2  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 29 30 31 32 34 35 36 37 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 56 57 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74] [ 3  9 28 33 38 54 55 58]
==
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 25
 26 27 28 31 32 33 34 35 36 37 38 39 40 41 42 43 45 46 47 48 49 50 51 52
 54 55 57 58 59 60 61 62 63 64 65 66 67 68 69 71 72 73 74] [ 1 20 29 30 44 53 56 70]
==
[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 58 59 60 61 62 63 66 67 68 70 71 73 74] [ 5 22 40 57 64 65 69 72]
==
[ 0  1  2  3  4  5  6  7  8  9 11 12 14 15 16 17 18 19 20 22 23 

Qu'est-ce qui est affiché ?

7. Faites de même avec des objets des classes `StratifiedKFold` et `LeaveOneOut`
et vérifiez que, même en ne mélangeant pas les données (c'est-à-dire sans
spécifier `shuffle=True`), les découpages obtenus sont différents.

In [15]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=10, shuffle=True)
for train, valid in cv.split(X_train, y_train):
    print(train, valid, end='\n==\n')

[ 1  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26 27
 28 29 31 32 33 34 35 36 37 38 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 59 60 61 62 64 65 66 67 69 70 71 72 73 74] [ 0  5  7 19 30 39 58 63 68]
==
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 26 27 28 29 30 31 32 33 34 36 37 39 40 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59 60 61 62 63 65 66 68 69 70 72 73] [25 35 38 41 64 67 71 74]
==
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24 25
 26 27 30 31 32 33 34 35 36 37 38 39 40 41 43 44 45 46 47 48 49 50 51 52
 53 55 56 57 58 61 62 63 64 65 66 67 68 69 70 71 72 73 74] [ 6 23 28 29 42 54 59 60]
==
[ 0  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20 21 22 23 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 46 48 49 50 51 52 53
 54 55 56 58 59 60 61 62 63 64 65 67 68 69 70 71 72 73 74] [ 1 10 24 44 45 47 57 66]
==
[ 0  1  3  4  5  6  7  9 10 11 12 13 14 17 18 19 20 21 22 23 24 

In [16]:
from sklearn.model_selection import LeaveOneOut

cv = LeaveOneOut()
for train, valid in cv.split(X_train, y_train):
    print(train, valid, end='\n==\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74] [0]
==
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74] [1]
==
[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74] [2]
==
[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74] [3]
==
[ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 

# Sélection de modèle

En pratique, vous n'utiliserez pas vous même ces appels aux méthodes `split()`
des itérateurs de validation croisée, car il existe dans `sklearn` un outil
très pratique pour vous aider lors de votre étape de sélection de modèle.

Cet outil s'appelle
[`GridSearchCV`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).
Là encore, il s'agit d'une classe `sklearn`, et vous l'utiliserez quasiment de
la même manière qu'un classifieur, à la nuance près des paramètres que vous
passerez lors de la construction d'une nouvelle instance.
Nous verrons dans ce TD trois de ces paramètres :

* `estimator` est un classifieur (créé mais pas encore appris sur des données) ;
* `param_grid` est une grille d'hyper-paramètres à tester pour ce classifieur ;
* `cv` est un itérateur de validation croisée, tel que l'un de ceux définis à la
section précédente.

Le paramètre `param_grid` est un dictionnaire (ou une liste de dictionnaire,
comme on le verra plus tard) dont les clés sont les noms des hyper-paramètres à
faire varier et les valeurs associées sont des listes de valeurs à
tester[^1].

8. Reprenez le cas d'un classifieur SVM linéaire et faites varier
l'hyper-paramètre `C` entre 1 et 10 (en prenant 5 valeurs espacées
    régulièrement).

In [21]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1,3,5,7,10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ('linear', 'rbf'), 'C': [1, 3, 5, 7, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

9. Affichez les paramètres du modèle choisi par la validation croisée. Évaluez
les performances de ce modèle sur votre jeu de test.

In [22]:
sorted(clf.cv_results_.items())

[('mean_fit_time',
  array([0.0004495 , 0.00059867, 0.00046277, 0.00048161, 0.0003775 ,
         0.00039887, 0.00030891, 0.00036001, 0.00030915, 0.00034976])),
 ('mean_score_time',
  array([0.00029564, 0.00044354, 0.00031686, 0.00030096, 0.00023858,
         0.00022205, 0.00019312, 0.00022539, 0.0001874 , 0.00020067])),
 ('mean_test_score',
  array([0.98      , 0.97333333, 0.96666667, 0.98      , 0.96666667,
         0.98      , 0.96666667, 0.98      , 0.97333333, 0.98      ])),
 ('mean_train_score',
  array([0.98999802, 0.98336304, 0.98336304, 0.98009507, 0.98336304,
         0.98336304, 0.97999604, 0.98336304, 0.97999604, 0.97999604])),
 ('param_C', masked_array(data=[1, 1, 3, 3, 5, 5, 7, 7, 10, 10],
               mask=[False, False, False, False, False, False, False, False,
                     False, False],
         fill_value='?',
              dtype=object)),
 ('param_kernel',
  masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                     'linear',

10. Parfois, certains hyper-paramètres sont liés entre eux. Dans le cas du SVM
par exemple, le choix d'un noyau implique de régler certains hyper-paramètres
spécifiques (_ex._ : le paramètre `gamma` du noyau Gaussien). Dans ce cas, on
peut définir `param_grid` comme une liste de dictionnaires, chaque dictionnaire
correspondant à un cas de figure. Utilisez cette possibilité pour choisir le
meilleur modèle pour votre problème entre un SVM linéaire et un SVM à noyau
Gaussien (pour les deux, on fera varier `C` entre 1 et 10, et pour le noyau Gaussien, on fera de plus varier `gamma` entre 10<sup>-2</sup> et 100 sur une échelle logarithmique).

In [30]:
parameters = {'kernel':('linear', 'rbf'), 'C': np.linspace(1,10,5), 'gamma':np.logspace(-2,2,5)}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)
clf.best_params_.items()        

dict_items([('C', 1.0), ('gamma', 0.01), ('kernel', 'linear')])

11. Étendez cette approche à un autre classifieur supervisé de votre choix et
comparez ses performances à celles du meilleur modèle SVM trouvé jusqu'alors.

# La notion de _Pipeline_

Bien souvent, pour mettre en oeuvre une solution de _machine learning_, vous
allez passer par plusieurs étapes successives de transformation de vos données
avant de les fournir à votre classifieur. Il est possible que ces
pré-traitements aient, eux aussi, des hyper-paramètres à régler. Pour pouvoir
sereinement prendre en compte toutes les configurations possibles, `sklearn`
définit la notion de
[`Pipeline`](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html).

12. Modifiez vos données d'origine pour mettre des `numpy.nan` à toutes les
valeurs plus grandes que 2 (en valeur absolue).

13. Créez un _pipeline_ qui soit constitué des 3 étapes suivantes :
a. une imputation des valeurs manquantes ;
b. une standardisation des données ;
c. une classification supervisée par un classifieur de votre choix.

14. Mettez en place une validation croisée qui permette de choisir si
l'imputation doit se faire par valeurs médianes ou moyennes et qui détermine
également un ou plusieurs hyper-paramètres du classifieur que vous avez choisi.

15. Chargez maintenant de nouvelles données à l'aide de la fonction
[`load_digits`](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html)
du module `sklearn.datasets`.
Imaginez un _pipeline_ qui consiste à effectuer tout d'abord une ACP sur ces
données puis une régression logistique dans l'espace de l'ACP.
Mettez en place une validation croisée pour choisir de manière optimale les
paramètres de ces deux étapes de votre _pipeline_.
Comparez votre solution à celle disponible
[là](http://scikit-learn.org/stable/auto_examples/plot_digits_pipe.html).

[^1]: Pour générer ces listes, on pourra avoir recours aux fonctions [`numpy.linspace`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linspace.html) et [`numpy.logspace`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.logspace.html).